### ISSUE TITLE
Untracked Transaction Replacement from External Wallets

### ISSUE THREAD

**Issue by Tima0203** [bgd-labs/fe-shared#42]
_**Issue Description:**_
When a transaction is modified through an external wallet bypassing the application, our application loses the capability to track the new transaction and only retains the original one. The original transaction remains in an unconfirmed state in the application and is no longer relevant to the actual state of the transaction on the blockchain.

Potential solutions, but both present certain challenges:

1. Checking User's Recent Transactions:
**_Approach:_** After a transaction doesn't settle on the blockchain, we can try fetching the user's latest transactions and comparing the nonce. If nonce, to, and callData match, it implies that the transaction was updated, and we can start tracking the new txHash. If only the nonce matches, we can mark the transaction as canceled. If no txHash found and nonce doesn't match, try to find it in mempool and restart processing.
**_Challenge:_** Deciding the right moment to check for transaction updates, either after a certain time or depending on some status. Additionally, the new transaction might linger in the mempool for a while, potentially requiring multiple RPC requests to locate it.
**_Cons:_**
❌ Difficulty in determining the optimal time for verification.
❌ The high computational and cost (in terms of RPC calls) of searching transactions in both blocks and the mempool.

2. Subscribing to New Transactions:
**_Approach_**: Once it's evident that the original transaction hasn't settled (same difficulty to determine when), we can subscribe to new transactions. If a new transaction with the same nonce from the same user appears, we process it.
**_Challenge:_** Implementing a filter for new transactions based on the user isn't feasible, forcing us to inspect all transactions, each one necessitating an RPC request, which is highly inefficient.
**_Cons:_**
❌ Absence of user-based transaction filtering.
❌ Too many RPC calls

3. Check User's Total Transaction Count:
**_Approach:_** At a given interval or trigger, we can check the total number of transactions sent by the user. If this number exceeds the transaction's nonce, it could suggest that the transaction might have been updated. If this is the case, locate the transaction and process it.
**_Challenge:_** Determining the specific scenario to inspect the total transaction count can be tricky. Identifying and isolating the exact transaction of interest among all transactions can also be challenging. There's a considerable probability that the count changed because a transaction was made in a different context, which is unrelated to our application.
**_Cons:_**
❌ Difficulty in identifying the precise scenario to check transaction counts.
❌ Challenge in locating the exact transaction among all user transactions.
❌ The change in transaction count might not always be relevant to our application's context.

In light of these challenges, we need to brainstorm other potential solutions or improvements to the existing ones to effectively track and manage externally modified transactions.

**Comment by Argeare5** [comment]
@Tima0203 After research this issue, I realized that it would be a good option to migrate from `ethers.js` and `@web3-react` to `view` and `wagmi`
and also solve this problem during migration using this https://wagmi.sh/core/actions/waitForTransaction#onreplaced-optional
